### ISSUE TITLE
ParseException template lacks serialversionUID field

### ISSUE THREAD

**Issue by sjaenick** [tulipcc/ParserGeneratorCC#36]
Hi there,

since Exceptions are serializable, a `serialversionUID` field should be present. This seems already fixed
upstream, see

https://github.com/javacc/javacc/blob/master/src/main/resources/templates/ParseException.template#L12

**Comment by phax** [comment]
In case a serializable class does not contain a `serialVersionUID` the Java runtime will automatically create a unique `serialVersionUID` value at runtime - see https://docs.oracle.com/javase/7/docs/platform/serialization/spec/class.html#4100

> The serialVersionUID is computed using the signature of a stream of bytes that reflect the class definition.

**Comment by sjaenick** [comment]
Interesting, I stumbled across this when updating maven-compiler-plugin in my projects to 3.11.0, which starts to
warn about this.

Thanks for the clarification.

**Comment by phax** [comment]
No worries. Better to be safe then sorry and thanks for pointing it out :)
